### ISSUE TITLE
Don't delete local posts on logout

### ISSUE THREAD

**Issue by AngeloStavrow** [writeas/writefreely-swiftui-multiplatform#106]
Currently, when logging out of the app, the entire local store is purged — without warning. That's really unpleasant UX, especially if you want to log in and out of multiple accounts. Instead, on logout, the app could:

1. Present an alert indicating that only local posts will be preserved
2. Provide the user an option to cancel logout so they can publish any local changes to published posts

**Comment by thebaer** [comment]
Yep, this sounds like a good solution!

I also think we should aim to limit alerts overall (as with the rest of the app) and only show one if absolutely needed. So ideally if a user has no locally edited published posts at all, we should skip the alert entirely and simply log out.

Along these lines, we could be extra helpful by telling them exactly how many published posts have local edits that will be lost, e.g. "Note: logging out will erase local / unpublished edits on 7 of your posts. Continue?"

**Comment by AngeloStavrow** [comment]
@thebaer That should be doable. In Apple's HIG, though, both [action sheets](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/) and [alerts](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/) should use as few words as possible.

Maybe, rather than making it part of a confirmation alert, that could be part of the log-out view? Something like this:

<img src="https://user-images.githubusercontent.com/387655/96891982-2d522300-1457-11eb-8392-ca21f5d3537a.png" width="390px" />

Could you tell me a bit more about what you're optimizing for in indicating how many locally-edited posts there are here? I feel like maybe it's sufficient for the user to see the above when they open the sheet to log out, as they can then dismiss it and have a quick swipe through the All Posts list to check. Is that sufficient, or does it miss some key UX case that I'm not thinking about?

**Comment by thebaer** [comment]
That does look good! But I'm optimizing for lower cognitive load on the user by only telling them information they absolutely need to know.

From the user's perspective, upon logout I care about a single thing and nothing else: _When do I lose the work I created?_ With this issue solved, I'll **only** lose my work when I have 1 or more "Edited" posts. Otherwise I don't actually need know or do anything else, because I already assume:

* when logging out, my account posts will be removed from my device, and
* work that doesn't belong to my account won't disappear along with it (to be solved here in #106).

So the point of the alert is to _help users make the correct decision_ with the question we've posed, i.e. "Do I log out anyway, or go back and look at my All Posts list?"

Telling them "You'll lose edits on _x_ posts by logging out" is just one way to do it -- maybe there's something else we could say. But the goal is to help them make the right decision to either evaporate their work (by logging out) or go back and salvage anything they want to keep.

**Comment by AngeloStavrow** [comment]
Okay, that works for me!

I'll propose that we keep this UI change I showed above as _generally useful info_ since you'll see it when you log in; when you tap the **Log Out** button, you will then receive an alert saying something like:

```
+---------------------------------------------+
|                   LOG OUT                   |
|---------------------------------------------|
| You'll lose unpublished changes to 6 edited |
| posts. Are you sure you want to continue?   |
|---------------------------------------------|
|         Cancel       |       Log Out        |
+---------------------------------------------+
```

What do you think about that flow?

**Comment by thebaer** [comment]
Alert flow looks perfect :+1:

I'm okay with keeping the UI change if we can also move the "Log out" action to the bottom of the Settings sheet. My concern is that while logging _in_ is important enough to be front-and-center, logging _out_ is an infrequent, low-priority action, and we ultimately don't want extra information to bury other more important settings on this screen.

**Comment by AngeloStavrow** [comment]
Cool. On the Mac, the log-in/log-out view is in one tab and the preferences stuff is in another tab, so making this change iOS-only is pretty straightforward, I think.

**Comment by AngeloStavrow** [comment]
As discussed in Slack, we'll set aside that "informational view" in the logout screen.
