### ISSUE TITLE
Display text in the editor based on the published appearance setting

### ISSUE THREAD

**Issue by AngeloStavrow** [writeas/writefreely-swiftui-multiplatform#15]
This is ~~a stretch goal for~~ an extension of #14, which only sets what font the Post will use after publishing. It'd be nice to show this change in the PostEditorView as well.

**Comment by thebaer** [comment]
As mentioned on our call, I think this is crucial for the 1.0 beta -- users will want to see the same fonts they're used to on the web. A minimum implementation might be:

* Use our "serif" font ([Lora](http://www.cyreal.org/2012/07/lora/)) for editor text on all local drafts (since this is the setting they publish with)
* For remote Posts, set the editor text font according to its `appearance` property

Beyond that, we can allow the user to set the post appearance, as outlined in #14.
