### ISSUE TITLE
Posts deleted from the server cannot be removed from the device

### ISSUE THREAD

**Issue by AngeloStavrow** [writeas/writefreely-swiftui-multiplatform#45]
While we probably don't want a post deleted from the server to get _automatically_ removed from the user's device, there should be something similar to the "remote post is newer" warning that allows the user to either:

1. restore the remote copy by publishing the local copy, or
2. delete the local copy as well

**Comment by thebaer** [comment]
Do we need to do anything on the server-side to support this? For example:

* Allow client to ask server for a list of posts deleted since _x_ time last synced (more complicated implementation needed on server, but more efficient on client), or

* Allow client to ask server for current list of posts (e.g. only IDs), so client can compare with local list and mark necessary posts deleted (easier on server-side, but inefficient and possibly slow on client)

**Comment by AngeloStavrow** [comment]
Good question! There aren't enough posts in my own WF account to really see any kind of performance hit one way or the other, I don't think, so it'll be interesting to get this in the hands of testers with hundreds or even thousands of posts. That said, whatever is decided on should probably be implemented in the Swift package. 

(Similarly, we could maybe think about implementing something like this for fetching updated posts from the server too, rather than calling the Swift package's `getPosts` method to get and cycle through to see what might have been updated.)
